name: skinclassifier
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  get: ^4.6.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.2
  image_picker: ^1.0.4
  google_nav_bar: ^5.0.6
  provider:
  firebase_core: ^2.19.0
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  tflite: ^1.1.2
  meta: ^1.9.1
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
      color: "#FFEFE7"
      image: assets/logo.png
      android: true
      ios: true
  
flutter:
  uses-material-design: true

  assets:
  - assets/
  - lib/images/
  - assets/labels.txt
  - assets/model_unquant.tflite